networks:
  52w-network:
services:
  redirect:
    container_name: 52w-redirect
    image: schmunk42/nginx-redirect
    ports:
      - "80:80"
    environment:
      - SERVER_REDIRECT=www.52walker.com
    logging:
      driver: "fluentd"
      options:
        tag: "{{.Name}}"
    depends_on:
      - fluentd
  fluentd:
    container_name: 52w-fluentd
    build:
      context: 'fluentd'
      dockerfile: Dockerfile
    ports:
      - '24224:24224' 
